### ISSUE TITLE
connection closed using terminal function but works through ssh

### ISSUE THREAD

**Issue by smashyalts** [moghtech/komodo#573]
![Image](https://github.com/user-attachments/assets/c101599d-17a2-4211-bc18-b3b3bb749b37)

![Image](https://github.com/user-attachments/assets/daa5a146-ca02-4a20-a97c-1a9aceb5de13)

if you need anything more, please lmk, its a fresh install of komodo, the periphery node im using is the one made when using the docker compose for core

**Comment by mbecker20** [comment]
Should be fixed in 1.18.3, before it wasn't using the correct container name when its using the default naming with the replica number on the end.

**Comment by sperlab** [comment]
Hi there. Just upgraded the whole stack (1 core, 15 peripheries) to `1.18.4` and still the same `connection closed` issue. All buddies are debian 12 based (docker is `5:28.3.1-1~debian.12~bookworm`)

**Comment by sperlab** [comment]
Fixed enabling websocket from the reverse proxy side (nginx)
```
proxy_set_header Upgrade $http_upgrade;
proxy_set_header Connection "upgrade";
proxy_http_version 1.1;
```
